version: '3.9'

services:
  redis:
    container_name: my_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  app:
    image: 'in-memory-db:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file: .env
    ports:
      - "8080:8080"
    environment:
      APPLICATION_PROPERTIES: $APPLICATION_PROPERTIES
    stdin_open: true
    tty: true
    depends_on:
      - redis
